package platts

type EWindowMarketData struct {
	Metadata struct {
		Count      int    `json:"count"`
		Pagesize   int    `json:"pagesize"`
		Page       int    `json:"page"`
		Maxid      string `json:"maxid"`
		TotalPages int    `json:"total_pages"`
		QueryTime  string `json:"query_time"`
	} `json:"metadata"`
	Results []struct {
		Market               []string    `json:"market"`
		Product              string      `json:"product"`
		Hub                  string      `json:"hub"`
		Strip                string      `json:"strip"`
		UpdateTime           string      `json:"update_time"`
		MarketMaker          string      `json:"market_maker"`
		OrderType            string      `json:"order_type"`
		OrderState           string      `json:"order_state"`
		Buyer                string      `json:"buyer,omitempty"`
		Seller               string      `json:"seller,omitempty"`
		Price                float64     `json:"price"`
		PriceUnit            string      `json:"price_unit"`
		OrderQuantity        int         `json:"order_quantity"`
		LotSize              int         `json:"lot_size"`
		LotUnit              string      `json:"lot_unit"`
		OrderBegin           string      `json:"order_begin"`
		OrderEnd             string      `json:"order_end"`
		OrderDate            string      `json:"order_date"`
		OrderTime            string      `json:"order_time"`
		OrderID              int         `json:"order_id"`
		OrderSequence        int         `json:"order_sequence"`
		DealID               interface{} `json:"deal_id"`
		DealBegin            interface{} `json:"deal_begin"`
		DealEnd              interface{} `json:"deal_end"`
		DealQuantity         interface{} `json:"deal_quantity"`
		DealQuantityMin      interface{} `json:"deal_quantity_min"`
		DealQuantityMax      interface{} `json:"deal_quantity_max"`
		DealTerms            interface{} `json:"deal_terms"`
		CounterpartyParent   interface{} `json:"counterparty_parent"`
		Counterparty         interface{} `json:"counterparty"`
		MarketMakerParent    string      `json:"market_maker_parent"`
		BuyerParent          interface{} `json:"buyer_parent"`
		SellerParent         interface{} `json:"seller_parent"`
		BuyerMnemonic        interface{} `json:"buyer_mnemonic"`
		SellerMnemonic       interface{} `json:"seller_mnemonic"`
		MarketMakerMnemonic  string      `json:"market_maker_mnemonic"`
		CounterpartyMnemonic interface{} `json:"counterparty_mnemonic"`
		WindowRegion         string      `json:"window_region"`
		MarketShortCode      []string    `json:"market_short_code"`
		MarketType           string      `json:"market_type"`
		C1PriceBasis         interface{} `json:"c1_price_basis"`
		C1Percentage         int         `json:"c1_percentage"`
		C1Price              int         `json:"c1_price"`
		C1BasisPeriod        interface{} `json:"c1_basis_period"`
		C1BasisPeriodDetails interface{} `json:"c1_basis_period_details"`
		C2PriceBasis         interface{} `json:"c2_price_basis"`
		C2Percentage         int         `json:"c2_percentage"`
		C2Price              int         `json:"c2_price"`
		C2BasisPeriod        interface{} `json:"c2_basis_period"`
		C2BasisPeriodDetails interface{} `json:"c2_basis_period_details"`
		C3PriceBasis         interface{} `json:"c3_price_basis"`
		C3Percentage         int         `json:"c3_percentage"`
		C3Price              int         `json:"c3_price"`
		C3BasisPeriod        interface{} `json:"c3_basis_period"`
		C3BasisPeriodDetails interface{} `json:"c3_basis_period_details"`
		WindowState          string      `json:"window_state"`
		OrderClassification  interface{} `json:"order_classification"`
		OcoOrderID           interface{} `json:"oco_order_id"`
		ReferenceOrderID     interface{} `json:"reference_order_id"`
		OrderPlattsID        int         `json:"order_platts_id"`
		OrderCancelled       string      `json:"order_cancelled"`
		OrderDerived         string      `json:"order_derived"`
		OrderQuantityTotal   int         `json:"order_quantity_total"`
		OrderRepeat          string      `json:"order_repeat"`
		LegPrices            interface{} `json:"leg_prices"`
		ParentDealID         interface{} `json:"parent_deal_id"`
		OrderSpread          string      `json:"order_spread"`
		OrderStateDetail     string      `json:"order_state_detail"`
	} `json:"results"`
}
